name: apn
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  dieklingel_core_shared:
    git: 
      url: https://github.com/KoiFresh/dieklingel-core.git
      ref: develop
      path: packages/shared
  hive: ^2.2.3
  http: ^0.13.5
  interpolation: ^2.1.2
  path: ^1.8.3
  uuid: ^3.0.7
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
