# This file sould be located at $HOME/dieklingel/config.yaml. It is used for
# the shared standartd settings for all packages. This is a sample
# configuration, which explains every propertie.

mqtt:
  uri: mqtt://server.dieklingel.com:1883/com.dieklingel/mayer/kai/
  username: ''
  password: ''

gui:
  viewport:
    clip:
      top: 15
      right: 35
      bottom: 10
      left: 10
  # configuration for signs displayed on the main page
  signs:
    - identifier: default
      file: /abs/path/file<.lottie>|<.json>|<.html>|<.png>|<.jpeg>|<.jpg>
      sound: /abs/path/file<.wav>|<.mp3>
    - identifier: default2
      file: /abs/path/file.<lottie>|<.json>|<.html>|<.png>|<.jpeg>|<.jpg>
      sound: /abs/path/file<.wav>|<.mp3>
  screensaver:
    # timeout in seconds when the screen will switch to inactive state
    timeout: 10
    enabled: true
    file: /abs/path/file.<lottie>|<.json>|<.html>|<.png>|<.jpeg>|<.jpg>

rtc:
  ice-servers:
    - urls: stun:stun1.l.google.com:19302
    - urls: stun:stun1.l.google.com:19302
      username: adsa
      credentials: ada

apn:
  url: https://fcm-worker.dieklingel.workers.dev/fcm/send
  title: 'Jemand steht vor deiner Tuer!' 
  body: '{DAY}-{MONTH}-{YEAR} {HOUR}:{MINUTE}:{SECOND}'

