name: exec
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.4.1
  path: ^1.8.3
  uuid: ^3.0.7
  yaml: ^3.1.1
  mqtt:
    path: ../../libraries/mqtt
